name: Build LaTeX document
on:
  push:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
